modLoader="javafml"
loaderVersion="[3,]"
issueTrackerURL="https://github.com/ClmentCch/RakuForge/issues"
logoFile="rakuforge_logo.png"
license="LGPL v2.1"

[[mods]]
    modId="rakuforge"
    # We use the global RakuForge version
    version="${global.neoForgeVersion}"
    displayName="RakuForge"
    credits="Anyone who has contributed to the project and supports our development"
    authors="The RakuForge Team"
    description='''
    RakuForge, a new Minecraft modding compatibility platform powered by innovation.
    '''

[[mixins]]
    config = "rakuforge.mixins.json"