@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.neoforged.neoforge.common.resources;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
