neoforge_version=${version}
neoform_version=${minecraft_version}-${neoform_version}
minecraft_version=${minecraft_version}
build_type=${build_type}
autoinstall_patches=net/neoforged/neoforge/common/patches.lzma