name: Run PR gametests

on:
  pull_request:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      # GradleUtils will append the branch name to the version,
      # but for that we need a properly checked out branch
      - name: Create branch for commit
        run:
          git switch -C pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: setup
          cache-read-only: false

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :tests:runGameTestServer
          cache-read-only: false
